source 'https://github.com/RisingSSR/RisingCyxbsSepc.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'RyScheduleCustomEdit_Example' do
  pod 'RyScheduleCustomEdit', :path => '../'

  target 'RyScheduleCustomEdit_Tests' do
    inherit! :search_paths

    
  end
end
