use_frameworks!

platform :ios, '10.0'

target 'RyScheduleCustomEdit_Example' do
  pod 'RyScheduleCustomEdit', :path => '../'

  target 'RyScheduleCustomEdit_Tests' do
    inherit! :search_paths

    
  end
end
